name: CI/CD Pipeline

on:
  pull_request:
  push:
    tags:
      - "*"

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Go environment
        uses: actions/setup-go@v2
        with:
          go-version: 1.23

      - name: Cache Go modules to speed up builds
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Lint the code
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

      - name: Install dependencies
        run: go mod tidy

      - name: Run unit tests
        run: go test -v ./...

      - name: Build the binary
        run: go build -o futil ./cmd

      - name: Upload the built binary as a release asset
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
