name: ci

on:
  pull_request:
    branches:
        - "*"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # ref: https://github.com/tomerm-iguazio/mlrun/blob/9f5d3eb0ba66681387df656ed980332042ac3163/.github/workflows/ci.yaml#L54
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version-file: "**/go.mod"
          cache-dependency-path: "**/go.sum"
          cache: true

      - name: Run Go Linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

  tests:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version-file: "**/go.mod"
          cache-dependency-path: "**/go.sum"
          cache: true

      - name: Run Go Tests
        run: go test -v ./...
