name: release

on:
  push:
    tags:
      - "*"

jobs:
  lint_and_test:
    uses: ./.github/workflows/ci.yml

  build:
    needs: lint_and_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version-file: "**/go.mod"
          cache-dependency-path: "**/go.sum"
          cache: true

      - name: Build the binary
        run: go build -o futil ./cmd

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version-file: "**/go.mod"
          cache-dependency-path: "**/go.sum"
          cache: true

      - name: Upload the built binary as a release asset
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
